### PR TITLE
Feature/edit user

### PR DESCRIPTION
**Pull request by subutux**
Hi!

I've implemented the edit user call. Because how the API expects to receive the edit call, I've made the assumption that a user would like to unset an attribute if he sets the attribute to `null`.

Let me know if assume otherwise :)

### Added

-   `User::edit()`
-   `User::batchEdit()`

### Confirmation

By sending this pull request I accept the following conditions:

-   [x] I have read the code of conduct and accept it.
-   [x] I have read the contributing guidelines and accept them.
-   [x] I accept that my contribution will be licensed under the AGPLv3.

### CODE REVIEW

**Comment by subutux** [comment]
pinging @bheisig 

I would love this to be merged.

**Comment by bheisig** [comment]
Hi @subutux,

Thank you very much for your PR. And sorry for the late response. Your implementation looks good. Can you provide some tests?

**Comment by bheisig** [comment]
Unfortunately not. Are you able to test it against your own environment?

**Comment by bheisig** [comment]
:+1:

Please remove the remaining `var_dump()` and I'll merge it :slightly_smiling_face:

**Pull request merged**
