### PR TITLE
Fixed problem with empty objects in json

### PR DESCRIPTION
**Pull request by skekec1**
Short description

Problem while parsing empty objects in json "{}"

### Changed

-   src/Python.php
  - {} added to list of elements

### Confirmation

By sending this pull request I accept the following conditions:

-   [x] I have read the code of conduct and accept it.
-   [x] I have read the contributing guidelines and accept them.
-   [x] I accept that my contribution will be licensed under the AGPLv3.

### CODE REVIEW

**Comment by skekec1** [comment]
Hi @bheisig,

this PR fixes a problem in the Pytho-JSON-Parser if there are empty objects as value like "{}".

**Comment by bheisig** [comment]
Hi @skekec1,

Thanks for your contribution! And: Sorry for the late response. Your change looks good. Only one small but important thing is missing: Can you please provide at least one unit test for your change? Similar ones can be found in `tests/PythonTest.php`

**Comment by skekec1** [comment]
Hi @bheisig,

i expanded the existing provider to cover this special case now. Is it fine now?

**Comment by bheisig** [comment]
Thanks, @skekec1! Looks good :+1:

**Pull request merged**
